FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build 

FROM nginxinc/nginx-unprivileged:alpine
# copy the built files from stage 1
COPY --from=builder /app/dist /usr/share/nginx/html
# copy the custom nginx configuration to fix 404 routing problem
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx","-g","daemon off;"]


